name: Deploy 

on: 
  push:
    branches:
      - main 
    paths:
      - /**

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - name: Build Docker Containers
          run:  docker-compose -f "docker-compose.yml" up -d --build